---
title: "Example dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}

library(tidyverse)
library(plotly)
library(vdemdata)

vdem2 <- vdem %>% 
  select(country_name, year, # Country and year are units in the dataset, so I definitely need them
         contains("v2casoe"), # Was a national state of emergency in place at any point this year?
         contains("v2regsupgroupssize"), # In total, how large is the percentage share of the domestic adult (18+) population that belongs to the political regime’s supporting groups?
         contains("v2elsuffrage"), # What percentage (%) of adult citizens (as defined by statute) has the legal right to vote in national elections?
         contains("v3cllabrig")) # Does labor enjoy the right to organize freely and bargain collectively?

```

### Chart A

```{r}

vdem2 %>%
  filter(country_name == "Norway") %>%
  plot_ly(x = ~year, 
          y = ~v2regsupgroupssize_mean, 
          name = "Percentage of population in regime main supporting group", # Giving name to the line being plotted
          type = "scatter", 
          mode = "lines") %>% # Specifying that we want lines 
  add_lines(y = ~v2elsuffrage, # Add an extra line to the plot, plotting the variable v2elsuffrage as well
            name = "Percentage of adult population with the right to vote", # Giving name to the second line being plotted
            mode = 'lines') %>% # Specifying that this should be lines, not markers (dots)
  layout(xaxis = list(title = ""), 
         yaxis = list(title = ""),
         legend = list(orientation = "v", # Wanting the legend to list the categories vertically ("v")
                       x = 0, y = 1.1)) # Placing the legend at these coordinates in the plot (play around to find the right customization)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

vdem2 %>%
  mutate(v2casoe_1 = ifelse(v2casoe_1 < 0.5, "Emergency", "Non-emergency")) %>%
  plot_ly(x = ~v2casoe_1,
          y = ~v2regsupgroupssize_mean,
          type = "box") %>%
  layout(xaxis = list(title = ""),
         yaxis = list(title = "Percentage of population in regime main supporting group"))

```

### Chart C

```{r}

vdem2 %>%
  mutate(v2casoe_1 = ifelse(v2casoe_1 < 0.5, "Emergency", "Non-emergency")) %>% # Recoding the v2casoe_1 variable to become "Emergency" if the value is over 0.5 and "Non-emergency" if the value is below 0.5
  drop_na(v2casoe_1) %>% # Removing all missing variables from the v2casoe_1 variable
  plot_ly(x = ~v2elsuffrage, # Setting the percentage of the population with suffrage to x-axis
          y = ~v2regsupgroupssize_mean, # Percentage of population in regime main supporting group on y-axis
          color = ~v2casoe_1, # Setting the colors of the dots to whether there was an emergency
          colors = c("blue", "orange"), # Specifying colors to blue and orange
          text = ~paste(country_name, year), # Adding a variable used to hover over the dots, pasting together values from the country_name variable and year variable
          hoverinfo = "text", # Using this hoverinfo variable to display when hovering over dots
          type = "scatter", # Telling R that we want a scatterplot
          mode = "markers", # Telling R that we want dots, not lines
          alpha = 0.2) %>% # Adding some dot transparency
  layout(xaxis = list(title = "Share of adult population with the right to vote"),
         yaxis = list(title = "Percentage of population in regime main supporting group"))

```

### Chart D

```{r}

vdem2 %>%
  filter(country_name %in% c("Spain", "Portugal", "Italy", "Greece")) %>%
  filter(year %in% c(1880, 1950, 1980)) %>%
  plot_ly(x = ~country_name, 
          y = ~v2elsuffrage, 
          group = ~year, 
          color = ~factor(year),
          type = "bar") %>% 
  layout(xaxis = list(title = ""), 
         yaxis = list(title = "Share of adult population with the right to vote"),
         plot_bgcolor = "lightgrey") 

```

